import jsPDF from "jspdf";

export interface LabPdfOrder {
  id: string;
  created_at: string;
  completed_at?: string | null;
  priority?: string | null;
  status?: string | null;
  notes?: string | null;
  tests?: string[] | null;
  patient?: { first_name?: string; last_name?: string; mrn?: string; pmr_no?: string | null } | null;
  doctor?: { display_name?: string | null; specialization?: string | null } | null;
  results?: Array<{
    test_name: string; value?: string | null; unit?: string | null;
    reference_range?: string | null; flag?: string | null;
  }>;
}

export function downloadLabReportPdf(order: LabPdfOrder, hospitalName = "Hospital", mode: "save" | "print" = "save") {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  let y = 40;

  doc.setFontSize(18); doc.setFont("helvetica", "bold");
  doc.text(hospitalName, w / 2, y, { align: "center" });
  y += 22;
  doc.setFontSize(12); doc.setFont("helvetica", "normal");
  doc.text("Laboratory Report", w / 2, y, { align: "center" });
  y += 24;

  doc.setDrawColor(180); doc.line(40, y, w - 40, y); y += 16;

  doc.setFontSize(10);
  const patient = order.patient
    ? `${order.patient.first_name ?? ""} ${order.patient.last_name ?? ""}`.trim()
    : "—";
  const mrn = order.patient?.mrn ?? order.patient?.pmr_no ?? "—";
  const doctor = order.doctor?.display_name ?? "—";

  const meta: [string, string][] = [
    ["Order ID", order.id.slice(0, 8)],
    ["Patient", patient],
    ["MRN", String(mrn)],
    ["Ordered by", doctor + (order.doctor?.specialization ? ` (${order.doctor.specialization})` : "")],
    ["Ordered at", new Date(order.created_at).toLocaleString()],
    ["Completed at", order.completed_at ? new Date(order.completed_at).toLocaleString() : "—"],
    ["Priority", order.priority ?? "routine"],
    ["Status", order.status ?? "—"],
  ];
  meta.forEach(([k, v]) => {
    doc.setFont("helvetica", "bold"); doc.text(`${k}:`, 40, y);
    doc.setFont("helvetica", "normal"); doc.text(String(v), 140, y);
    y += 14;
  });
  y += 8;

  doc.setFont("helvetica", "bold"); doc.text("Results", 40, y); y += 14;
  doc.setDrawColor(220); doc.line(40, y, w - 40, y); y += 14;

  const cols = [
    { label: "Test", x: 40, width: 160 },
    { label: "Value", x: 200, width: 80 },
    { label: "Unit", x: 285, width: 60 },
    { label: "Reference", x: 350, width: 140 },
    { label: "Flag", x: 495, width: 60 },
  ];
  doc.setFont("helvetica", "bold"); doc.setFontSize(9);
  cols.forEach((c) => doc.text(c.label, c.x, y));
  y += 12;
  doc.setFont("helvetica", "normal");

  const results = order.results && order.results.length
    ? order.results
    : (order.tests ?? []).map((t) => ({ test_name: t, value: "—", unit: "", reference_range: "", flag: "" }));

  results.forEach((r) => {
    if (y > 760) { doc.addPage(); y = 60; }
    doc.text(String(r.test_name ?? "—"), cols[0].x, y, { maxWidth: cols[0].width });
    doc.text(String(r.value ?? "—"), cols[1].x, y, { maxWidth: cols[1].width });
    doc.text(String(r.unit ?? ""), cols[2].x, y, { maxWidth: cols[2].width });
    doc.text(String(r.reference_range ?? ""), cols[3].x, y, { maxWidth: cols[3].width });
    doc.text(String(r.flag ?? ""), cols[4].x, y, { maxWidth: cols[4].width });
    y += 14;
  });

  if (order.notes) {
    y += 12;
    doc.setFont("helvetica", "bold"); doc.text("Notes", 40, y); y += 12;
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(order.notes, w - 80);
    doc.text(lines, 40, y); y += lines.length * 12;
  }

  y = 800;
  doc.setDrawColor(180); doc.line(40, y, w - 40, y);
  doc.setFontSize(8); doc.setTextColor(120);
  doc.text("Generated by MediFlow AI · Lovable Cloud", w / 2, y + 12, { align: "center" });

  const safeName = (patient || "patient").replace(/\s+/g, "_");
  if (mode === "print") {
    doc.autoPrint();
    const url = doc.output("bloburl");
    window.open(url, "_blank");
  } else {
    doc.save(`Lab_${safeName}_${order.id.slice(0, 8)}.pdf`);
  }
}
