import { jsPDF } from "jspdf";

type Patient = {
  first_name?: string; last_name?: string; mrn?: string; dob?: string | null;
  gender?: string | null; blood_group?: string | null; phone?: string | null;
  cnic?: string | null; address?: string | null;
  allergies?: string[] | null; chronic_conditions?: string[] | null;
};
type Appt = { id: string; scheduled_at: string; status?: string; reason?: string | null };
type Rx = { id: string; issued_at: string; diagnosis?: string | null; medications?: any[] | null };

function ageFromDob(dob?: string | null) {
  if (!dob) return "—";
  const ms = Date.now() - new Date(dob).getTime();
  if (Number.isNaN(ms)) return "—";
  return Math.max(0, Math.floor(ms / (365.25 * 24 * 3600 * 1000))) + "y";
}

export function downloadPatientSummaryPdf(opts: {
  patient: Patient;
  appointments: Appt[];
  prescriptions: Rx[];
}) {
  const { patient, appointments, prescriptions } = opts;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 40;

  // Header band
  doc.setFillColor(220, 38, 38);
  doc.rect(0, 0, W, 60, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18); doc.setFont("helvetica", "bold");
  doc.text("Patient Summary", 40, 38);
  doc.setFontSize(10); doc.setFont("helvetica", "normal");
  doc.text(new Date().toLocaleString(), W - 40, 38, { align: "right" });

  doc.setTextColor(0, 0, 0);
  y = 90;

  // Identity block
  doc.setFontSize(14); doc.setFont("helvetica", "bold");
  doc.text(`${patient.first_name ?? ""} ${patient.last_name ?? ""}`.trim(), 40, y);
  doc.setFontSize(10); doc.setFont("helvetica", "normal");
  y += 16;
  const idLine = [
    patient.mrn && `MRN: ${patient.mrn}`,
    `Age: ${ageFromDob(patient.dob)}`,
    patient.gender && `Sex: ${patient.gender}`,
    patient.blood_group && `Blood: ${patient.blood_group}`,
    patient.phone && `Phone: ${patient.phone}`,
    patient.cnic && `CNIC: ${patient.cnic}`,
  ].filter(Boolean).join("  ·  ");
  doc.text(idLine, 40, y); y += 14;
  if (patient.address) { doc.text(`Address: ${patient.address}`, 40, y); y += 14; }

  // Allergies / chronic
  y += 8;
  doc.setFont("helvetica", "bold"); doc.text("Allergies", 40, y);
  doc.setFont("helvetica", "normal");
  doc.text((patient.allergies ?? []).join(", ") || "None recorded", 120, y);
  y += 14;
  doc.setFont("helvetica", "bold"); doc.text("Chronic", 40, y);
  doc.setFont("helvetica", "normal");
  doc.text((patient.chronic_conditions ?? []).join(", ") || "None recorded", 120, y);
  y += 20;

  // Last visits
  doc.setFont("helvetica", "bold"); doc.setFontSize(12);
  doc.text("Recent visits", 40, y); y += 14;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10);
  const visits = appointments.slice(0, 6);
  if (visits.length === 0) { doc.text("No visits recorded.", 40, y); y += 14; }
  for (const v of visits) {
    const line = `${new Date(v.scheduled_at).toLocaleDateString()}  ·  ${v.status ?? "—"}${v.reason ? `  ·  ${v.reason}` : ""}`;
    doc.text(line, 40, y); y += 13;
    if (y > 740) { doc.addPage(); y = 60; }
  }

  // Recent prescriptions
  y += 8;
  doc.setFont("helvetica", "bold"); doc.setFontSize(12);
  doc.text("Recent prescriptions", 40, y); y += 14;
  doc.setFont("helvetica", "normal"); doc.setFontSize(10);
  const rxs = prescriptions.slice(0, 5);
  if (rxs.length === 0) { doc.text("No prescriptions recorded.", 40, y); y += 14; }
  for (const r of rxs) {
    if (y > 720) { doc.addPage(); y = 60; }
    doc.setFont("helvetica", "bold");
    doc.text(`${new Date(r.issued_at).toLocaleDateString()}  ·  ${r.diagnosis || "—"}`, 40, y);
    y += 13; doc.setFont("helvetica", "normal");
    const meds = Array.isArray(r.medications) ? r.medications : [];
    for (const m of meds.slice(0, 6)) {
      const t = `• ${m.name ?? ""}${m.dose ? ` ${m.dose}` : ""}${m.frequency ? ` · ${m.frequency}` : ""}${m.duration ? ` · ${m.duration}` : ""}`;
      doc.text(t, 56, y); y += 12;
      if (y > 760) { doc.addPage(); y = 60; }
    }
    y += 4;
  }

  // Footer
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFontSize(8); doc.setTextColor(120, 120, 120);
  doc.text("Generated by MediFlow AI — for clinical reference only.", 40, pageH - 24);

  const fname = `patient-summary-${(patient.mrn ?? "patient").replace(/[^a-z0-9-]/gi, "_")}.pdf`;
  doc.save(fname);
}
