/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Master_adminRouteImport } from './routes/master_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FindDoctorRouteImport } from './routes/find-doctor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffDashboardRouteImport } from './routes/staff.dashboard'
import { Route as PatientSignupRouteImport } from './routes/patient.signup'
import { Route as PatientLoginRouteImport } from './routes/patient.login'
import { Route as PatientDashboardRouteImport } from './routes/patient.dashboard'
import { Route as Master_adminPlansRouteImport } from './routes/master_admin.plans'
import { Route as Master_adminMigrationsRouteImport } from './routes/master_admin.migrations'
import { Route as Master_adminHospitalsRouteImport } from './routes/master_admin.hospitals'
import { Route as Master_adminDashboardRouteImport } from './routes/master_admin.dashboard'
import { Route as Master_adminCredentialsRouteImport } from './routes/master_admin.credentials'
import { Route as Master_adminAnalyticsRouteImport } from './routes/master_admin.analytics'
import { Route as HospitalSlugRouteImport } from './routes/hospital.$slug'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as DoctorReportsRouteImport } from './routes/doctor.reports'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorMessagesRouteImport } from './routes/doctor.messages'
import { Route as DoctorEarningsRouteImport } from './routes/doctor.earnings'
import { Route as DoctorClosuresRouteImport } from './routes/doctor.closures'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as DoctorAiAssistantRouteImport } from './routes/doctor.ai-assistant'
import { Route as HospitalSlugIndexRouteImport } from './routes/hospital.$slug.index'
import { Route as HospitalSlugStaffRouteImport } from './routes/hospital.$slug.staff'
import { Route as HospitalSlugSettingsRouteImport } from './routes/hospital.$slug.settings'
import { Route as HospitalSlugScheduleRouteImport } from './routes/hospital.$slug.schedule'
import { Route as HospitalSlugReportsRouteImport } from './routes/hospital.$slug.reports'
import { Route as HospitalSlugRadiologyRouteImport } from './routes/hospital.$slug.radiology'
import { Route as HospitalSlugPharmacyRouteImport } from './routes/hospital.$slug.pharmacy'
import { Route as HospitalSlugPatientsRouteImport } from './routes/hospital.$slug.patients'
import { Route as HospitalSlugOpdRouteImport } from './routes/hospital.$slug.opd'
import { Route as HospitalSlugNotificationsRouteImport } from './routes/hospital.$slug.notifications'
import { Route as HospitalSlugMessagesRouteImport } from './routes/hospital.$slug.messages'
import { Route as HospitalSlugLabServicesRouteImport } from './routes/hospital.$slug.lab-services'
import { Route as HospitalSlugLabBillingRouteImport } from './routes/hospital.$slug.lab-billing'
import { Route as HospitalSlugLabRouteImport } from './routes/hospital.$slug.lab'
import { Route as HospitalSlugIpdRouteImport } from './routes/hospital.$slug.ipd'
import { Route as HospitalSlugFinancialControlsRouteImport } from './routes/hospital.$slug.financial-controls'
import { Route as HospitalSlugEarningsRouteImport } from './routes/hospital.$slug.earnings'
import { Route as HospitalSlugDoctorsRouteImport } from './routes/hospital.$slug.doctors'
import { Route as HospitalSlugDoctorSchedulesRouteImport } from './routes/hospital.$slug.doctor-schedules'
import { Route as HospitalSlugDaycareRouteImport } from './routes/hospital.$slug.daycare'
import { Route as HospitalSlugConcessionsRouteImport } from './routes/hospital.$slug.concessions'
import { Route as HospitalSlugCollectionsRouteImport } from './routes/hospital.$slug.collections'
import { Route as HospitalSlugClosuresRouteImport } from './routes/hospital.$slug.closures'
import { Route as HospitalSlugBloodRouteImport } from './routes/hospital.$slug.blood'
import { Route as HospitalSlugBillingRouteImport } from './routes/hospital.$slug.billing'
import { Route as HospitalSlugAuthRouteImport } from './routes/hospital.$slug.auth'
import { Route as HospitalSlugAuditRouteImport } from './routes/hospital.$slug.audit'
import { Route as HospitalSlugAppointmentsRouteImport } from './routes/hospital.$slug.appointments'
import { Route as HospitalSlugAiRouteImport } from './routes/hospital.$slug.ai'
import { Route as FindDoctorHospitalSlugDoctorIdRouteImport } from './routes/find-doctor_.$hospitalSlug.$doctorId'
import { Route as HospitalSlugPatientsPatientIdRouteImport } from './routes/hospital.$slug.patients.$patientId'

const Master_adminRoute = Master_adminRouteImport.update({
  id: '/master_admin',
  path: '/master_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FindDoctorRoute = FindDoctorRouteImport.update({
  id: '/find-doctor',
  path: '/find-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientSignupRoute = PatientSignupRouteImport.update({
  id: '/patient/signup',
  path: '/patient/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientLoginRoute = PatientLoginRouteImport.update({
  id: '/patient/login',
  path: '/patient/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientDashboardRoute = PatientDashboardRouteImport.update({
  id: '/patient/dashboard',
  path: '/patient/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Master_adminPlansRoute = Master_adminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => Master_adminRoute,
} as any)
const Master_adminMigrationsRoute = Master_adminMigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => Master_adminRoute,
} as any)
const Master_adminHospitalsRoute = Master_adminHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => Master_adminRoute,
} as any)
const Master_adminDashboardRoute = Master_adminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => Master_adminRoute,
} as any)
const Master_adminCredentialsRoute = Master_adminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => Master_adminRoute,
} as any)
const Master_adminAnalyticsRoute = Master_adminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => Master_adminRoute,
} as any)
const HospitalSlugRoute = HospitalSlugRouteImport.update({
  id: '/hospital/$slug',
  path: '/hospital/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/doctor/schedule',
  path: '/doctor/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorReportsRoute = DoctorReportsRouteImport.update({
  id: '/doctor/reports',
  path: '/doctor/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/doctor/patients',
  path: '/doctor/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorMessagesRoute = DoctorMessagesRouteImport.update({
  id: '/doctor/messages',
  path: '/doctor/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorEarningsRoute = DoctorEarningsRouteImport.update({
  id: '/doctor/earnings',
  path: '/doctor/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorClosuresRoute = DoctorClosuresRouteImport.update({
  id: '/doctor/closures',
  path: '/doctor/closures',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/doctor/appointments',
  path: '/doctor/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorAiAssistantRoute = DoctorAiAssistantRouteImport.update({
  id: '/doctor/ai-assistant',
  path: '/doctor/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalSlugIndexRoute = HospitalSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugStaffRoute = HospitalSlugStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugSettingsRoute = HospitalSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugScheduleRoute = HospitalSlugScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugReportsRoute = HospitalSlugReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugRadiologyRoute = HospitalSlugRadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugPharmacyRoute = HospitalSlugPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugPatientsRoute = HospitalSlugPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugOpdRoute = HospitalSlugOpdRouteImport.update({
  id: '/opd',
  path: '/opd',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugNotificationsRoute =
  HospitalSlugNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => HospitalSlugRoute,
  } as any)
const HospitalSlugMessagesRoute = HospitalSlugMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugLabServicesRoute = HospitalSlugLabServicesRouteImport.update({
  id: '/lab-services',
  path: '/lab-services',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugLabBillingRoute = HospitalSlugLabBillingRouteImport.update({
  id: '/lab-billing',
  path: '/lab-billing',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugLabRoute = HospitalSlugLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugIpdRoute = HospitalSlugIpdRouteImport.update({
  id: '/ipd',
  path: '/ipd',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugFinancialControlsRoute =
  HospitalSlugFinancialControlsRouteImport.update({
    id: '/financial-controls',
    path: '/financial-controls',
    getParentRoute: () => HospitalSlugRoute,
  } as any)
const HospitalSlugEarningsRoute = HospitalSlugEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugDoctorsRoute = HospitalSlugDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugDoctorSchedulesRoute =
  HospitalSlugDoctorSchedulesRouteImport.update({
    id: '/doctor-schedules',
    path: '/doctor-schedules',
    getParentRoute: () => HospitalSlugRoute,
  } as any)
const HospitalSlugDaycareRoute = HospitalSlugDaycareRouteImport.update({
  id: '/daycare',
  path: '/daycare',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugConcessionsRoute = HospitalSlugConcessionsRouteImport.update({
  id: '/concessions',
  path: '/concessions',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugCollectionsRoute = HospitalSlugCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugClosuresRoute = HospitalSlugClosuresRouteImport.update({
  id: '/closures',
  path: '/closures',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugBloodRoute = HospitalSlugBloodRouteImport.update({
  id: '/blood',
  path: '/blood',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugBillingRoute = HospitalSlugBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugAuthRoute = HospitalSlugAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugAuditRoute = HospitalSlugAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const HospitalSlugAppointmentsRoute =
  HospitalSlugAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => HospitalSlugRoute,
  } as any)
const HospitalSlugAiRoute = HospitalSlugAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => HospitalSlugRoute,
} as any)
const FindDoctorHospitalSlugDoctorIdRoute =
  FindDoctorHospitalSlugDoctorIdRouteImport.update({
    id: '/find-doctor_/$hospitalSlug/$doctorId',
    path: '/find-doctor/$hospitalSlug/$doctorId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HospitalSlugPatientsPatientIdRoute =
  HospitalSlugPatientsPatientIdRouteImport.update({
    id: '/$patientId',
    path: '/$patientId',
    getParentRoute: () => HospitalSlugPatientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-doctor': typeof FindDoctorRoute
  '/login': typeof LoginRoute
  '/master_admin': typeof Master_adminRouteWithChildren
  '/doctor/ai-assistant': typeof DoctorAiAssistantRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/closures': typeof DoctorClosuresRoute
  '/doctor/earnings': typeof DoctorEarningsRoute
  '/doctor/messages': typeof DoctorMessagesRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/hospital/$slug': typeof HospitalSlugRouteWithChildren
  '/master_admin/analytics': typeof Master_adminAnalyticsRoute
  '/master_admin/credentials': typeof Master_adminCredentialsRoute
  '/master_admin/dashboard': typeof Master_adminDashboardRoute
  '/master_admin/hospitals': typeof Master_adminHospitalsRoute
  '/master_admin/migrations': typeof Master_adminMigrationsRoute
  '/master_admin/plans': typeof Master_adminPlansRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/signup': typeof PatientSignupRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/find-doctor/$hospitalSlug/$doctorId': typeof FindDoctorHospitalSlugDoctorIdRoute
  '/hospital/$slug/ai': typeof HospitalSlugAiRoute
  '/hospital/$slug/appointments': typeof HospitalSlugAppointmentsRoute
  '/hospital/$slug/audit': typeof HospitalSlugAuditRoute
  '/hospital/$slug/auth': typeof HospitalSlugAuthRoute
  '/hospital/$slug/billing': typeof HospitalSlugBillingRoute
  '/hospital/$slug/blood': typeof HospitalSlugBloodRoute
  '/hospital/$slug/closures': typeof HospitalSlugClosuresRoute
  '/hospital/$slug/collections': typeof HospitalSlugCollectionsRoute
  '/hospital/$slug/concessions': typeof HospitalSlugConcessionsRoute
  '/hospital/$slug/daycare': typeof HospitalSlugDaycareRoute
  '/hospital/$slug/doctor-schedules': typeof HospitalSlugDoctorSchedulesRoute
  '/hospital/$slug/doctors': typeof HospitalSlugDoctorsRoute
  '/hospital/$slug/earnings': typeof HospitalSlugEarningsRoute
  '/hospital/$slug/financial-controls': typeof HospitalSlugFinancialControlsRoute
  '/hospital/$slug/ipd': typeof HospitalSlugIpdRoute
  '/hospital/$slug/lab': typeof HospitalSlugLabRoute
  '/hospital/$slug/lab-billing': typeof HospitalSlugLabBillingRoute
  '/hospital/$slug/lab-services': typeof HospitalSlugLabServicesRoute
  '/hospital/$slug/messages': typeof HospitalSlugMessagesRoute
  '/hospital/$slug/notifications': typeof HospitalSlugNotificationsRoute
  '/hospital/$slug/opd': typeof HospitalSlugOpdRoute
  '/hospital/$slug/patients': typeof HospitalSlugPatientsRouteWithChildren
  '/hospital/$slug/pharmacy': typeof HospitalSlugPharmacyRoute
  '/hospital/$slug/radiology': typeof HospitalSlugRadiologyRoute
  '/hospital/$slug/reports': typeof HospitalSlugReportsRoute
  '/hospital/$slug/schedule': typeof HospitalSlugScheduleRoute
  '/hospital/$slug/settings': typeof HospitalSlugSettingsRoute
  '/hospital/$slug/staff': typeof HospitalSlugStaffRoute
  '/hospital/$slug/': typeof HospitalSlugIndexRoute
  '/hospital/$slug/patients/$patientId': typeof HospitalSlugPatientsPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-doctor': typeof FindDoctorRoute
  '/login': typeof LoginRoute
  '/master_admin': typeof Master_adminRouteWithChildren
  '/doctor/ai-assistant': typeof DoctorAiAssistantRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/closures': typeof DoctorClosuresRoute
  '/doctor/earnings': typeof DoctorEarningsRoute
  '/doctor/messages': typeof DoctorMessagesRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/master_admin/analytics': typeof Master_adminAnalyticsRoute
  '/master_admin/credentials': typeof Master_adminCredentialsRoute
  '/master_admin/dashboard': typeof Master_adminDashboardRoute
  '/master_admin/hospitals': typeof Master_adminHospitalsRoute
  '/master_admin/migrations': typeof Master_adminMigrationsRoute
  '/master_admin/plans': typeof Master_adminPlansRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/signup': typeof PatientSignupRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/find-doctor/$hospitalSlug/$doctorId': typeof FindDoctorHospitalSlugDoctorIdRoute
  '/hospital/$slug/ai': typeof HospitalSlugAiRoute
  '/hospital/$slug/appointments': typeof HospitalSlugAppointmentsRoute
  '/hospital/$slug/audit': typeof HospitalSlugAuditRoute
  '/hospital/$slug/auth': typeof HospitalSlugAuthRoute
  '/hospital/$slug/billing': typeof HospitalSlugBillingRoute
  '/hospital/$slug/blood': typeof HospitalSlugBloodRoute
  '/hospital/$slug/closures': typeof HospitalSlugClosuresRoute
  '/hospital/$slug/collections': typeof HospitalSlugCollectionsRoute
  '/hospital/$slug/concessions': typeof HospitalSlugConcessionsRoute
  '/hospital/$slug/daycare': typeof HospitalSlugDaycareRoute
  '/hospital/$slug/doctor-schedules': typeof HospitalSlugDoctorSchedulesRoute
  '/hospital/$slug/doctors': typeof HospitalSlugDoctorsRoute
  '/hospital/$slug/earnings': typeof HospitalSlugEarningsRoute
  '/hospital/$slug/financial-controls': typeof HospitalSlugFinancialControlsRoute
  '/hospital/$slug/ipd': typeof HospitalSlugIpdRoute
  '/hospital/$slug/lab': typeof HospitalSlugLabRoute
  '/hospital/$slug/lab-billing': typeof HospitalSlugLabBillingRoute
  '/hospital/$slug/lab-services': typeof HospitalSlugLabServicesRoute
  '/hospital/$slug/messages': typeof HospitalSlugMessagesRoute
  '/hospital/$slug/notifications': typeof HospitalSlugNotificationsRoute
  '/hospital/$slug/opd': typeof HospitalSlugOpdRoute
  '/hospital/$slug/patients': typeof HospitalSlugPatientsRouteWithChildren
  '/hospital/$slug/pharmacy': typeof HospitalSlugPharmacyRoute
  '/hospital/$slug/radiology': typeof HospitalSlugRadiologyRoute
  '/hospital/$slug/reports': typeof HospitalSlugReportsRoute
  '/hospital/$slug/schedule': typeof HospitalSlugScheduleRoute
  '/hospital/$slug/settings': typeof HospitalSlugSettingsRoute
  '/hospital/$slug/staff': typeof HospitalSlugStaffRoute
  '/hospital/$slug': typeof HospitalSlugIndexRoute
  '/hospital/$slug/patients/$patientId': typeof HospitalSlugPatientsPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-doctor': typeof FindDoctorRoute
  '/login': typeof LoginRoute
  '/master_admin': typeof Master_adminRouteWithChildren
  '/doctor/ai-assistant': typeof DoctorAiAssistantRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/closures': typeof DoctorClosuresRoute
  '/doctor/earnings': typeof DoctorEarningsRoute
  '/doctor/messages': typeof DoctorMessagesRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/hospital/$slug': typeof HospitalSlugRouteWithChildren
  '/master_admin/analytics': typeof Master_adminAnalyticsRoute
  '/master_admin/credentials': typeof Master_adminCredentialsRoute
  '/master_admin/dashboard': typeof Master_adminDashboardRoute
  '/master_admin/hospitals': typeof Master_adminHospitalsRoute
  '/master_admin/migrations': typeof Master_adminMigrationsRoute
  '/master_admin/plans': typeof Master_adminPlansRoute
  '/patient/dashboard': typeof PatientDashboardRoute
  '/patient/login': typeof PatientLoginRoute
  '/patient/signup': typeof PatientSignupRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/find-doctor_/$hospitalSlug/$doctorId': typeof FindDoctorHospitalSlugDoctorIdRoute
  '/hospital/$slug/ai': typeof HospitalSlugAiRoute
  '/hospital/$slug/appointments': typeof HospitalSlugAppointmentsRoute
  '/hospital/$slug/audit': typeof HospitalSlugAuditRoute
  '/hospital/$slug/auth': typeof HospitalSlugAuthRoute
  '/hospital/$slug/billing': typeof HospitalSlugBillingRoute
  '/hospital/$slug/blood': typeof HospitalSlugBloodRoute
  '/hospital/$slug/closures': typeof HospitalSlugClosuresRoute
  '/hospital/$slug/collections': typeof HospitalSlugCollectionsRoute
  '/hospital/$slug/concessions': typeof HospitalSlugConcessionsRoute
  '/hospital/$slug/daycare': typeof HospitalSlugDaycareRoute
  '/hospital/$slug/doctor-schedules': typeof HospitalSlugDoctorSchedulesRoute
  '/hospital/$slug/doctors': typeof HospitalSlugDoctorsRoute
  '/hospital/$slug/earnings': typeof HospitalSlugEarningsRoute
  '/hospital/$slug/financial-controls': typeof HospitalSlugFinancialControlsRoute
  '/hospital/$slug/ipd': typeof HospitalSlugIpdRoute
  '/hospital/$slug/lab': typeof HospitalSlugLabRoute
  '/hospital/$slug/lab-billing': typeof HospitalSlugLabBillingRoute
  '/hospital/$slug/lab-services': typeof HospitalSlugLabServicesRoute
  '/hospital/$slug/messages': typeof HospitalSlugMessagesRoute
  '/hospital/$slug/notifications': typeof HospitalSlugNotificationsRoute
  '/hospital/$slug/opd': typeof HospitalSlugOpdRoute
  '/hospital/$slug/patients': typeof HospitalSlugPatientsRouteWithChildren
  '/hospital/$slug/pharmacy': typeof HospitalSlugPharmacyRoute
  '/hospital/$slug/radiology': typeof HospitalSlugRadiologyRoute
  '/hospital/$slug/reports': typeof HospitalSlugReportsRoute
  '/hospital/$slug/schedule': typeof HospitalSlugScheduleRoute
  '/hospital/$slug/settings': typeof HospitalSlugSettingsRoute
  '/hospital/$slug/staff': typeof HospitalSlugStaffRoute
  '/hospital/$slug/': typeof HospitalSlugIndexRoute
  '/hospital/$slug/patients/$patientId': typeof HospitalSlugPatientsPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-doctor'
    | '/login'
    | '/master_admin'
    | '/doctor/ai-assistant'
    | '/doctor/appointments'
    | '/doctor/closures'
    | '/doctor/earnings'
    | '/doctor/messages'
    | '/doctor/patients'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/hospital/$slug'
    | '/master_admin/analytics'
    | '/master_admin/credentials'
    | '/master_admin/dashboard'
    | '/master_admin/hospitals'
    | '/master_admin/migrations'
    | '/master_admin/plans'
    | '/patient/dashboard'
    | '/patient/login'
    | '/patient/signup'
    | '/staff/dashboard'
    | '/find-doctor/$hospitalSlug/$doctorId'
    | '/hospital/$slug/ai'
    | '/hospital/$slug/appointments'
    | '/hospital/$slug/audit'
    | '/hospital/$slug/auth'
    | '/hospital/$slug/billing'
    | '/hospital/$slug/blood'
    | '/hospital/$slug/closures'
    | '/hospital/$slug/collections'
    | '/hospital/$slug/concessions'
    | '/hospital/$slug/daycare'
    | '/hospital/$slug/doctor-schedules'
    | '/hospital/$slug/doctors'
    | '/hospital/$slug/earnings'
    | '/hospital/$slug/financial-controls'
    | '/hospital/$slug/ipd'
    | '/hospital/$slug/lab'
    | '/hospital/$slug/lab-billing'
    | '/hospital/$slug/lab-services'
    | '/hospital/$slug/messages'
    | '/hospital/$slug/notifications'
    | '/hospital/$slug/opd'
    | '/hospital/$slug/patients'
    | '/hospital/$slug/pharmacy'
    | '/hospital/$slug/radiology'
    | '/hospital/$slug/reports'
    | '/hospital/$slug/schedule'
    | '/hospital/$slug/settings'
    | '/hospital/$slug/staff'
    | '/hospital/$slug/'
    | '/hospital/$slug/patients/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/find-doctor'
    | '/login'
    | '/master_admin'
    | '/doctor/ai-assistant'
    | '/doctor/appointments'
    | '/doctor/closures'
    | '/doctor/earnings'
    | '/doctor/messages'
    | '/doctor/patients'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/master_admin/analytics'
    | '/master_admin/credentials'
    | '/master_admin/dashboard'
    | '/master_admin/hospitals'
    | '/master_admin/migrations'
    | '/master_admin/plans'
    | '/patient/dashboard'
    | '/patient/login'
    | '/patient/signup'
    | '/staff/dashboard'
    | '/find-doctor/$hospitalSlug/$doctorId'
    | '/hospital/$slug/ai'
    | '/hospital/$slug/appointments'
    | '/hospital/$slug/audit'
    | '/hospital/$slug/auth'
    | '/hospital/$slug/billing'
    | '/hospital/$slug/blood'
    | '/hospital/$slug/closures'
    | '/hospital/$slug/collections'
    | '/hospital/$slug/concessions'
    | '/hospital/$slug/daycare'
    | '/hospital/$slug/doctor-schedules'
    | '/hospital/$slug/doctors'
    | '/hospital/$slug/earnings'
    | '/hospital/$slug/financial-controls'
    | '/hospital/$slug/ipd'
    | '/hospital/$slug/lab'
    | '/hospital/$slug/lab-billing'
    | '/hospital/$slug/lab-services'
    | '/hospital/$slug/messages'
    | '/hospital/$slug/notifications'
    | '/hospital/$slug/opd'
    | '/hospital/$slug/patients'
    | '/hospital/$slug/pharmacy'
    | '/hospital/$slug/radiology'
    | '/hospital/$slug/reports'
    | '/hospital/$slug/schedule'
    | '/hospital/$slug/settings'
    | '/hospital/$slug/staff'
    | '/hospital/$slug'
    | '/hospital/$slug/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/find-doctor'
    | '/login'
    | '/master_admin'
    | '/doctor/ai-assistant'
    | '/doctor/appointments'
    | '/doctor/closures'
    | '/doctor/earnings'
    | '/doctor/messages'
    | '/doctor/patients'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/hospital/$slug'
    | '/master_admin/analytics'
    | '/master_admin/credentials'
    | '/master_admin/dashboard'
    | '/master_admin/hospitals'
    | '/master_admin/migrations'
    | '/master_admin/plans'
    | '/patient/dashboard'
    | '/patient/login'
    | '/patient/signup'
    | '/staff/dashboard'
    | '/find-doctor_/$hospitalSlug/$doctorId'
    | '/hospital/$slug/ai'
    | '/hospital/$slug/appointments'
    | '/hospital/$slug/audit'
    | '/hospital/$slug/auth'
    | '/hospital/$slug/billing'
    | '/hospital/$slug/blood'
    | '/hospital/$slug/closures'
    | '/hospital/$slug/collections'
    | '/hospital/$slug/concessions'
    | '/hospital/$slug/daycare'
    | '/hospital/$slug/doctor-schedules'
    | '/hospital/$slug/doctors'
    | '/hospital/$slug/earnings'
    | '/hospital/$slug/financial-controls'
    | '/hospital/$slug/ipd'
    | '/hospital/$slug/lab'
    | '/hospital/$slug/lab-billing'
    | '/hospital/$slug/lab-services'
    | '/hospital/$slug/messages'
    | '/hospital/$slug/notifications'
    | '/hospital/$slug/opd'
    | '/hospital/$slug/patients'
    | '/hospital/$slug/pharmacy'
    | '/hospital/$slug/radiology'
    | '/hospital/$slug/reports'
    | '/hospital/$slug/schedule'
    | '/hospital/$slug/settings'
    | '/hospital/$slug/staff'
    | '/hospital/$slug/'
    | '/hospital/$slug/patients/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindDoctorRoute: typeof FindDoctorRoute
  LoginRoute: typeof LoginRoute
  Master_adminRoute: typeof Master_adminRouteWithChildren
  DoctorAiAssistantRoute: typeof DoctorAiAssistantRoute
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorClosuresRoute: typeof DoctorClosuresRoute
  DoctorEarningsRoute: typeof DoctorEarningsRoute
  DoctorMessagesRoute: typeof DoctorMessagesRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorReportsRoute: typeof DoctorReportsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  HospitalSlugRoute: typeof HospitalSlugRouteWithChildren
  PatientDashboardRoute: typeof PatientDashboardRoute
  PatientLoginRoute: typeof PatientLoginRoute
  PatientSignupRoute: typeof PatientSignupRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  FindDoctorHospitalSlugDoctorIdRoute: typeof FindDoctorHospitalSlugDoctorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/master_admin': {
      id: '/master_admin'
      path: '/master_admin'
      fullPath: '/master_admin'
      preLoaderRoute: typeof Master_adminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-doctor': {
      id: '/find-doctor'
      path: '/find-doctor'
      fullPath: '/find-doctor'
      preLoaderRoute: typeof FindDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/signup': {
      id: '/patient/signup'
      path: '/patient/signup'
      fullPath: '/patient/signup'
      preLoaderRoute: typeof PatientSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/login': {
      id: '/patient/login'
      path: '/patient/login'
      fullPath: '/patient/login'
      preLoaderRoute: typeof PatientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/dashboard': {
      id: '/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof PatientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master_admin/plans': {
      id: '/master_admin/plans'
      path: '/plans'
      fullPath: '/master_admin/plans'
      preLoaderRoute: typeof Master_adminPlansRouteImport
      parentRoute: typeof Master_adminRoute
    }
    '/master_admin/migrations': {
      id: '/master_admin/migrations'
      path: '/migrations'
      fullPath: '/master_admin/migrations'
      preLoaderRoute: typeof Master_adminMigrationsRouteImport
      parentRoute: typeof Master_adminRoute
    }
    '/master_admin/hospitals': {
      id: '/master_admin/hospitals'
      path: '/hospitals'
      fullPath: '/master_admin/hospitals'
      preLoaderRoute: typeof Master_adminHospitalsRouteImport
      parentRoute: typeof Master_adminRoute
    }
    '/master_admin/dashboard': {
      id: '/master_admin/dashboard'
      path: '/dashboard'
      fullPath: '/master_admin/dashboard'
      preLoaderRoute: typeof Master_adminDashboardRouteImport
      parentRoute: typeof Master_adminRoute
    }
    '/master_admin/credentials': {
      id: '/master_admin/credentials'
      path: '/credentials'
      fullPath: '/master_admin/credentials'
      preLoaderRoute: typeof Master_adminCredentialsRouteImport
      parentRoute: typeof Master_adminRoute
    }
    '/master_admin/analytics': {
      id: '/master_admin/analytics'
      path: '/analytics'
      fullPath: '/master_admin/analytics'
      preLoaderRoute: typeof Master_adminAnalyticsRouteImport
      parentRoute: typeof Master_adminRoute
    }
    '/hospital/$slug': {
      id: '/hospital/$slug'
      path: '/hospital/$slug'
      fullPath: '/hospital/$slug'
      preLoaderRoute: typeof HospitalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/doctor/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/reports': {
      id: '/doctor/reports'
      path: '/doctor/reports'
      fullPath: '/doctor/reports'
      preLoaderRoute: typeof DoctorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/messages': {
      id: '/doctor/messages'
      path: '/doctor/messages'
      fullPath: '/doctor/messages'
      preLoaderRoute: typeof DoctorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/earnings': {
      id: '/doctor/earnings'
      path: '/doctor/earnings'
      fullPath: '/doctor/earnings'
      preLoaderRoute: typeof DoctorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/closures': {
      id: '/doctor/closures'
      path: '/doctor/closures'
      fullPath: '/doctor/closures'
      preLoaderRoute: typeof DoctorClosuresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/ai-assistant': {
      id: '/doctor/ai-assistant'
      path: '/doctor/ai-assistant'
      fullPath: '/doctor/ai-assistant'
      preLoaderRoute: typeof DoctorAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/$slug/': {
      id: '/hospital/$slug/'
      path: '/'
      fullPath: '/hospital/$slug/'
      preLoaderRoute: typeof HospitalSlugIndexRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/staff': {
      id: '/hospital/$slug/staff'
      path: '/staff'
      fullPath: '/hospital/$slug/staff'
      preLoaderRoute: typeof HospitalSlugStaffRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/settings': {
      id: '/hospital/$slug/settings'
      path: '/settings'
      fullPath: '/hospital/$slug/settings'
      preLoaderRoute: typeof HospitalSlugSettingsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/schedule': {
      id: '/hospital/$slug/schedule'
      path: '/schedule'
      fullPath: '/hospital/$slug/schedule'
      preLoaderRoute: typeof HospitalSlugScheduleRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/reports': {
      id: '/hospital/$slug/reports'
      path: '/reports'
      fullPath: '/hospital/$slug/reports'
      preLoaderRoute: typeof HospitalSlugReportsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/radiology': {
      id: '/hospital/$slug/radiology'
      path: '/radiology'
      fullPath: '/hospital/$slug/radiology'
      preLoaderRoute: typeof HospitalSlugRadiologyRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/pharmacy': {
      id: '/hospital/$slug/pharmacy'
      path: '/pharmacy'
      fullPath: '/hospital/$slug/pharmacy'
      preLoaderRoute: typeof HospitalSlugPharmacyRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/patients': {
      id: '/hospital/$slug/patients'
      path: '/patients'
      fullPath: '/hospital/$slug/patients'
      preLoaderRoute: typeof HospitalSlugPatientsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/opd': {
      id: '/hospital/$slug/opd'
      path: '/opd'
      fullPath: '/hospital/$slug/opd'
      preLoaderRoute: typeof HospitalSlugOpdRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/notifications': {
      id: '/hospital/$slug/notifications'
      path: '/notifications'
      fullPath: '/hospital/$slug/notifications'
      preLoaderRoute: typeof HospitalSlugNotificationsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/messages': {
      id: '/hospital/$slug/messages'
      path: '/messages'
      fullPath: '/hospital/$slug/messages'
      preLoaderRoute: typeof HospitalSlugMessagesRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/lab-services': {
      id: '/hospital/$slug/lab-services'
      path: '/lab-services'
      fullPath: '/hospital/$slug/lab-services'
      preLoaderRoute: typeof HospitalSlugLabServicesRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/lab-billing': {
      id: '/hospital/$slug/lab-billing'
      path: '/lab-billing'
      fullPath: '/hospital/$slug/lab-billing'
      preLoaderRoute: typeof HospitalSlugLabBillingRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/lab': {
      id: '/hospital/$slug/lab'
      path: '/lab'
      fullPath: '/hospital/$slug/lab'
      preLoaderRoute: typeof HospitalSlugLabRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/ipd': {
      id: '/hospital/$slug/ipd'
      path: '/ipd'
      fullPath: '/hospital/$slug/ipd'
      preLoaderRoute: typeof HospitalSlugIpdRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/financial-controls': {
      id: '/hospital/$slug/financial-controls'
      path: '/financial-controls'
      fullPath: '/hospital/$slug/financial-controls'
      preLoaderRoute: typeof HospitalSlugFinancialControlsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/earnings': {
      id: '/hospital/$slug/earnings'
      path: '/earnings'
      fullPath: '/hospital/$slug/earnings'
      preLoaderRoute: typeof HospitalSlugEarningsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/doctors': {
      id: '/hospital/$slug/doctors'
      path: '/doctors'
      fullPath: '/hospital/$slug/doctors'
      preLoaderRoute: typeof HospitalSlugDoctorsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/doctor-schedules': {
      id: '/hospital/$slug/doctor-schedules'
      path: '/doctor-schedules'
      fullPath: '/hospital/$slug/doctor-schedules'
      preLoaderRoute: typeof HospitalSlugDoctorSchedulesRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/daycare': {
      id: '/hospital/$slug/daycare'
      path: '/daycare'
      fullPath: '/hospital/$slug/daycare'
      preLoaderRoute: typeof HospitalSlugDaycareRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/concessions': {
      id: '/hospital/$slug/concessions'
      path: '/concessions'
      fullPath: '/hospital/$slug/concessions'
      preLoaderRoute: typeof HospitalSlugConcessionsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/collections': {
      id: '/hospital/$slug/collections'
      path: '/collections'
      fullPath: '/hospital/$slug/collections'
      preLoaderRoute: typeof HospitalSlugCollectionsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/closures': {
      id: '/hospital/$slug/closures'
      path: '/closures'
      fullPath: '/hospital/$slug/closures'
      preLoaderRoute: typeof HospitalSlugClosuresRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/blood': {
      id: '/hospital/$slug/blood'
      path: '/blood'
      fullPath: '/hospital/$slug/blood'
      preLoaderRoute: typeof HospitalSlugBloodRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/billing': {
      id: '/hospital/$slug/billing'
      path: '/billing'
      fullPath: '/hospital/$slug/billing'
      preLoaderRoute: typeof HospitalSlugBillingRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/auth': {
      id: '/hospital/$slug/auth'
      path: '/auth'
      fullPath: '/hospital/$slug/auth'
      preLoaderRoute: typeof HospitalSlugAuthRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/audit': {
      id: '/hospital/$slug/audit'
      path: '/audit'
      fullPath: '/hospital/$slug/audit'
      preLoaderRoute: typeof HospitalSlugAuditRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/appointments': {
      id: '/hospital/$slug/appointments'
      path: '/appointments'
      fullPath: '/hospital/$slug/appointments'
      preLoaderRoute: typeof HospitalSlugAppointmentsRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/hospital/$slug/ai': {
      id: '/hospital/$slug/ai'
      path: '/ai'
      fullPath: '/hospital/$slug/ai'
      preLoaderRoute: typeof HospitalSlugAiRouteImport
      parentRoute: typeof HospitalSlugRoute
    }
    '/find-doctor_/$hospitalSlug/$doctorId': {
      id: '/find-doctor_/$hospitalSlug/$doctorId'
      path: '/find-doctor/$hospitalSlug/$doctorId'
      fullPath: '/find-doctor/$hospitalSlug/$doctorId'
      preLoaderRoute: typeof FindDoctorHospitalSlugDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/$slug/patients/$patientId': {
      id: '/hospital/$slug/patients/$patientId'
      path: '/$patientId'
      fullPath: '/hospital/$slug/patients/$patientId'
      preLoaderRoute: typeof HospitalSlugPatientsPatientIdRouteImport
      parentRoute: typeof HospitalSlugPatientsRoute
    }
  }
}

interface Master_adminRouteChildren {
  Master_adminAnalyticsRoute: typeof Master_adminAnalyticsRoute
  Master_adminCredentialsRoute: typeof Master_adminCredentialsRoute
  Master_adminDashboardRoute: typeof Master_adminDashboardRoute
  Master_adminHospitalsRoute: typeof Master_adminHospitalsRoute
  Master_adminMigrationsRoute: typeof Master_adminMigrationsRoute
  Master_adminPlansRoute: typeof Master_adminPlansRoute
}

const Master_adminRouteChildren: Master_adminRouteChildren = {
  Master_adminAnalyticsRoute: Master_adminAnalyticsRoute,
  Master_adminCredentialsRoute: Master_adminCredentialsRoute,
  Master_adminDashboardRoute: Master_adminDashboardRoute,
  Master_adminHospitalsRoute: Master_adminHospitalsRoute,
  Master_adminMigrationsRoute: Master_adminMigrationsRoute,
  Master_adminPlansRoute: Master_adminPlansRoute,
}

const Master_adminRouteWithChildren = Master_adminRoute._addFileChildren(
  Master_adminRouteChildren,
)

interface HospitalSlugPatientsRouteChildren {
  HospitalSlugPatientsPatientIdRoute: typeof HospitalSlugPatientsPatientIdRoute
}

const HospitalSlugPatientsRouteChildren: HospitalSlugPatientsRouteChildren = {
  HospitalSlugPatientsPatientIdRoute: HospitalSlugPatientsPatientIdRoute,
}

const HospitalSlugPatientsRouteWithChildren =
  HospitalSlugPatientsRoute._addFileChildren(HospitalSlugPatientsRouteChildren)

interface HospitalSlugRouteChildren {
  HospitalSlugAiRoute: typeof HospitalSlugAiRoute
  HospitalSlugAppointmentsRoute: typeof HospitalSlugAppointmentsRoute
  HospitalSlugAuditRoute: typeof HospitalSlugAuditRoute
  HospitalSlugAuthRoute: typeof HospitalSlugAuthRoute
  HospitalSlugBillingRoute: typeof HospitalSlugBillingRoute
  HospitalSlugBloodRoute: typeof HospitalSlugBloodRoute
  HospitalSlugClosuresRoute: typeof HospitalSlugClosuresRoute
  HospitalSlugCollectionsRoute: typeof HospitalSlugCollectionsRoute
  HospitalSlugConcessionsRoute: typeof HospitalSlugConcessionsRoute
  HospitalSlugDaycareRoute: typeof HospitalSlugDaycareRoute
  HospitalSlugDoctorSchedulesRoute: typeof HospitalSlugDoctorSchedulesRoute
  HospitalSlugDoctorsRoute: typeof HospitalSlugDoctorsRoute
  HospitalSlugEarningsRoute: typeof HospitalSlugEarningsRoute
  HospitalSlugFinancialControlsRoute: typeof HospitalSlugFinancialControlsRoute
  HospitalSlugIpdRoute: typeof HospitalSlugIpdRoute
  HospitalSlugLabRoute: typeof HospitalSlugLabRoute
  HospitalSlugLabBillingRoute: typeof HospitalSlugLabBillingRoute
  HospitalSlugLabServicesRoute: typeof HospitalSlugLabServicesRoute
  HospitalSlugMessagesRoute: typeof HospitalSlugMessagesRoute
  HospitalSlugNotificationsRoute: typeof HospitalSlugNotificationsRoute
  HospitalSlugOpdRoute: typeof HospitalSlugOpdRoute
  HospitalSlugPatientsRoute: typeof HospitalSlugPatientsRouteWithChildren
  HospitalSlugPharmacyRoute: typeof HospitalSlugPharmacyRoute
  HospitalSlugRadiologyRoute: typeof HospitalSlugRadiologyRoute
  HospitalSlugReportsRoute: typeof HospitalSlugReportsRoute
  HospitalSlugScheduleRoute: typeof HospitalSlugScheduleRoute
  HospitalSlugSettingsRoute: typeof HospitalSlugSettingsRoute
  HospitalSlugStaffRoute: typeof HospitalSlugStaffRoute
  HospitalSlugIndexRoute: typeof HospitalSlugIndexRoute
}

const HospitalSlugRouteChildren: HospitalSlugRouteChildren = {
  HospitalSlugAiRoute: HospitalSlugAiRoute,
  HospitalSlugAppointmentsRoute: HospitalSlugAppointmentsRoute,
  HospitalSlugAuditRoute: HospitalSlugAuditRoute,
  HospitalSlugAuthRoute: HospitalSlugAuthRoute,
  HospitalSlugBillingRoute: HospitalSlugBillingRoute,
  HospitalSlugBloodRoute: HospitalSlugBloodRoute,
  HospitalSlugClosuresRoute: HospitalSlugClosuresRoute,
  HospitalSlugCollectionsRoute: HospitalSlugCollectionsRoute,
  HospitalSlugConcessionsRoute: HospitalSlugConcessionsRoute,
  HospitalSlugDaycareRoute: HospitalSlugDaycareRoute,
  HospitalSlugDoctorSchedulesRoute: HospitalSlugDoctorSchedulesRoute,
  HospitalSlugDoctorsRoute: HospitalSlugDoctorsRoute,
  HospitalSlugEarningsRoute: HospitalSlugEarningsRoute,
  HospitalSlugFinancialControlsRoute: HospitalSlugFinancialControlsRoute,
  HospitalSlugIpdRoute: HospitalSlugIpdRoute,
  HospitalSlugLabRoute: HospitalSlugLabRoute,
  HospitalSlugLabBillingRoute: HospitalSlugLabBillingRoute,
  HospitalSlugLabServicesRoute: HospitalSlugLabServicesRoute,
  HospitalSlugMessagesRoute: HospitalSlugMessagesRoute,
  HospitalSlugNotificationsRoute: HospitalSlugNotificationsRoute,
  HospitalSlugOpdRoute: HospitalSlugOpdRoute,
  HospitalSlugPatientsRoute: HospitalSlugPatientsRouteWithChildren,
  HospitalSlugPharmacyRoute: HospitalSlugPharmacyRoute,
  HospitalSlugRadiologyRoute: HospitalSlugRadiologyRoute,
  HospitalSlugReportsRoute: HospitalSlugReportsRoute,
  HospitalSlugScheduleRoute: HospitalSlugScheduleRoute,
  HospitalSlugSettingsRoute: HospitalSlugSettingsRoute,
  HospitalSlugStaffRoute: HospitalSlugStaffRoute,
  HospitalSlugIndexRoute: HospitalSlugIndexRoute,
}

const HospitalSlugRouteWithChildren = HospitalSlugRoute._addFileChildren(
  HospitalSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindDoctorRoute: FindDoctorRoute,
  LoginRoute: LoginRoute,
  Master_adminRoute: Master_adminRouteWithChildren,
  DoctorAiAssistantRoute: DoctorAiAssistantRoute,
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorClosuresRoute: DoctorClosuresRoute,
  DoctorEarningsRoute: DoctorEarningsRoute,
  DoctorMessagesRoute: DoctorMessagesRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorReportsRoute: DoctorReportsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  HospitalSlugRoute: HospitalSlugRouteWithChildren,
  PatientDashboardRoute: PatientDashboardRoute,
  PatientLoginRoute: PatientLoginRoute,
  PatientSignupRoute: PatientSignupRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  FindDoctorHospitalSlugDoctorIdRoute: FindDoctorHospitalSlugDoctorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
